controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

ackermann_steering_controller:
  ros__parameters:
    reference_timeout: 2.0
    front_steering: true
    open_loop: false 
    velocity_rolling_window_size: 10
    position_feedback: true
    use_stamped_vel: false
    
    steering_joints_names: [front_steer_left_joint, front_steer_right_joint]
    traction_joints_names: [rear_left_joint, rear_right_joint]

    wheelbase: 0.65142           # URDF: 0.37142 - (-0.28)
    steering_track_width: 0.585  # URDF: 0.29249 - (-0.29251) approx
    traction_track_width: 0.585
    
    traction_wheels_radius: 0.165 # URDF: 0.165
    steering_wheels_radius: 0.165

    enable_odom_tf: false
    base_frame_id: base_link
    odom_frame_id: odom
    publish_rate: 50.0
